### ISSUE TITLE
App crashes when trying to launch terminal (Permission denial when permission declared)

### ISSUE THREAD

**Issue by zacthespack** [jackpal/Android-Terminal-Emulator#390]
I am the creator of the LinuxonAndroid app, and finally got around to making the changes suggested in https://github.com/jackpal/Android-Terminal-Emulator/issues/374 to get my app working again.

So I have changed how we launch the intent from:

    Intent intent = new Intent(Intent.ACTION_MAIN);
    intent.setComponent(new ComponentName("jackpal.androidterm","jackpal.androidterm.RemoteInterface"));
    intent.setAction("jackpal.androidterm.RUN_SCRIPT");
    intent.putExtra("jackpal.androidterm.iInitialCommand", cmdString);
    startActivity(intent);

to:
    Intent intent = new Intent(Intent.ACTION_MAIN);
    intent.setAction("jackpal.androidterm.RUN_SCRIPT");
    intent.putExtra("jackpal.androidterm.iInitialCommand", cmdString);
    startActivity(intent);

However I now get:

>java.lang.RuntimeException: Unable to start activity >ComponentInfo{com.zpwebsites.linuxonandroid/com.zpwebsites.linuxonandroid.Widget_Activity}: >java.lang.SecurityException: Permission Denial: starting Intent { act=jackpal.androidterm.RUN_SCRIPT cmp=jackpal.androidterm/.RunScript (has extras) } from ProcessRecord{440c1080 5420:com.zpwebsites.linuxonandroid/u0a10147} (pid=5420, uid=10147) requires jackpal.androidterm.permission.RUN_SCRIPT
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2349)
at android.app.ActivityThread.access$700(ActivityThread.java:159)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:176)
at android.app.ActivityThread.main(ActivityThread.java:5419)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.SecurityException: Permission Denial: starting Intent { act=jackpal.androidterm.RUN_SCRIPT cmp=jackpal.androidterm/.RunScript (has extras) } from ProcessRecord{440c1080 5420:com.zpwebsites.linuxonandroid/u0a10147} (pid=5420, uid=10147) requires jackpal.androidterm.permission.RUN_SCRIPT
at android.os.Parcel.readException(Parcel.java:1431)
at android.os.Parcel.readException(Parcel.java:1385)
at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2242)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1436)
at android.app.Activity.startActivityForResult(Activity.java:3464)
at android.app.Activity.startActivityForResult(Activity.java:3425)
at android.app.Activity.startActivity(Activity.java:3661)
at android.app.Activity.startActivity(Activity.java:3629)
at com.zpwebsites.linuxonandroid.Widget_Activity.startLinux(Widget_Activity.java:154)
at com.zpwebsites.linuxonandroid.Widget_Activity.onCreate(Widget_Activity.java:103)
at android.app.Activity.performCreate(Activity.java:5372)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2257)
... 12 more

My manifest:

    <manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.zpwebsites.linuxonandroid"
    android:versionCode="51"
    android:versionName="2.8.1" >

    <uses-sdk
        android:minSdkVersion="8"
        android:targetSdkVersion="19" />
    <uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="jackpal.androidterm.permission.RUN_SCRIPT"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.ACCESS_SUPERUSER"/>

**Comment by FrankWestlake** [comment]
>java.lang.SecurityException: Permission Denial: starting Intent ... requires jackpal.androidterm.permission.RUN_SCRIPT

Confirm that you are testing this with  the

**Comment by FrankWestlake** [comment]
I was able to duplicate this SecurityException by replacing all periods (ASCII 2E) with U+2024 in the jackpal Intent action string. The two strings look identical. Some applications (like the Windows clipboard and web browsers) translate between Unicode and ASCII without warning, so a copy/paste of this string could have replaced the periods or the undercarriage ('_'). Please advise whether this is or is  not the cause. 

Frank
