### ISSUE TITLE
We may need to change the native library name again

### ISSUE THREAD

**Issue by jackpal** [jackpal/Android-Terminal-Emulator#403]
With version 1.0.66 people with custom ROMs are getting crashes. This tends to happen whenever we change the ABI of the native library, because the custom ROM's version of the library takes precedence over the version in the app.

The work-around is to change the name of the native library whenever we change the ABI.

I didn't think we changed the ABI, but enough crash reports are coming in that it's beginning to look like we did. (It never hurts to change the library name, we might want to change it every release anyway, just to avoid any possible problem. :-) )

**Comment by jackpal** [comment]
Here's the failure that one user is seeing.

D/AndroidRuntime(31616): Shutting down VM
E/AndroidRuntime(31616): FATAL EXCEPTION: main
E/AndroidRuntime(31616): Process: jackpal.androidterm, PID: 31616
E/AndroidRuntime(31616): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/app/TerminalEmulator/TerminalEmulator.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libjackpal-termexec.so"
E/AndroidRuntime(31616): 	at java.lang.Runtime.loadLibrary(Runtime.java:366)
E/AndroidRuntime(31616): 	at java.lang.System.loadLibrary(System.java:988)
E/AndroidRuntime(31616): 	at jackpal.androidterm.TermExec.<clinit>(TermExec.java:23)
E/AndroidRuntime(31616): 	at jackpal.androidterm.ShellTermSession.createSubprocess(ShellTermSession.java:153)
E/AndroidRuntime(31616): 	at jackpal.androidterm.ShellTermSession.initializeSession(ShellTermSession.java:101)
E/AndroidRuntime(31616): 	at jackpal.androidterm.ShellTermSession.<init>(ShellTermSession.java:57)
E/AndroidRuntime(31616): 	at jackpal.androidterm.Term.createTermSession(Term.java:502)
E/AndroidRuntime(31616): 	at jackpal.androidterm.Term.createTermSession(Term.java:511)
E/AndroidRuntime(31616): 	at jackpal.androidterm.Term.populateViewFlipper(Term.java:418)
E/AndroidRuntime(31616): 	at jackpal.androidterm.Term.access$400(Term.java:82)
E/AndroidRuntime(31616): 	at jackpal.androidterm.Term$2.onServiceConnected(Term.java:152)
E/AndroidRuntime(31616): 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1208)
E/AndroidRuntime(31616): 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1225)
E/AndroidRuntime(31616): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(31616): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(31616): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(31616): 	at android.app.ActivityThread.main(ActivityThread.java:5256)
E/AndroidRuntime(31616): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31616): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(31616): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(31616): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
W/ActivityManager(  475):   Force finishing activity 1 jackpal.androidterm/.Term

**Comment by jackpal** [comment]
Aha -- this is not our normal Play Store term.apk, it's some version built into a ROM.

**Comment by MathewCNichols** [comment]
In ticket #401, I use CyanogenMod 11 and I updated to v.1.0.66 via Google Play and received the error when trying to launch the app. There is a conflict with the updated Google Play Store app and the Term.apk installed as a system app in CM 11. I believe trying to launch the app after the update invokes the ROM to look for the missing libjackpal-termexec.so library in /system/lib.

I peeled out the Term.apk from /system/app, rebooted, and installed the Google Play App standalone. Since the app installed in user space /data, all worked well referencing the new libraries.

From this point I wanted to reinstall TEA as a system app again, as the ROM had it baked in before. I copied the new libraries "libjackpal-androidterm4.so" & "libjackpal-termexec.so" from /data/data/jackpal.androidterm/lib to /system/lib and reinstalled the Term.apk to /system/app and all is well once again!

Thanks, Jack!

**Comment by jackpal** [comment]
Yeah, I just reproduced this by installing Cyanogenmod on one my phones. I think the problem is that TEA now has _two_ native libraries: libjackpal-androidterm4.so" & "libjackpal-termexec.so". CyanogenMOD needs to update its installer to install both libraries.

**Comment by MathewCNichols** [comment]
Submitted in CyanogenMod bug tracker: https://jira.cyanogenmod.org/browse/CYAN-6465

**Comment by jackpal** [comment]
Thanks!

**Comment by jackpal** [comment]
Matthew, I've just submitted version 1.0.67 to the Play Store, which has yet another new set of library names. They are:

libjackpal-androidterm5.so
libjackpal-termexec2.so

So CyanogenMOD 11 will have to update again when it pulls in that version of TEA.

Hopefully that will be the last change to these libraries for a while.

**Comment by jackpal** [comment]
(I'll leave this bug open for a few days until CynaogenMOD 11 is updated to the v1.0.67 library names.)

**Comment by MathewCNichols** [comment]
Jack, Can I get these libraries on GitHub so I can drop them in my /system/lib folder?

Also, are the previous termexec and androidterm4 libraries necessary with the new libraries?

I'll be sure to update the CyanogenMod ticket as well.

**Comment by jackpal** [comment]
The latest version of the app on github, v1.0.67. does have the new libraries. (As does the new version in the store.)

You do not need to have any other versions of termexec or androidterm4

**Comment by MathewCNichols** [comment]
Ok, please forgive my noobishness. 

The app force close previously was a result of the libraries not upgrading in /system/lib when I updated to 1.0.66 through the play store. I had to remove the apk from /system/app and do a clean install of the Play Store app into user data space, copy the libraries from /data/app-lib into /system/lib, uninstall, then put the apk back into /system/app. 

I guess having the libraries at hand would save me the step removing the system app and installing the app into /data. I would just drop Tue libraries into /system/lib and upgrade through play store. No uninstalling and reinstalling to get libs. :D
